# Configuración de conexión a MariaDB para Spring Boot
spring.datasource.url=jdbc:mariadb://localhost:3306/vivigo_db
spring.datasource.username=root
spring.datasource.password=soley830
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Configuración JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Configuración del JWTUtils
secretKey=vivigoeslamejorapp12345678904208302025

# Configuración SMTP para Spring Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vivi.go777420@gmail.com
spring.mail.password=bohr gcep ackj lkld
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Configuración Cloudinary
cloud.name=dxvvp4ote
cloud.api.key=938831583477113
cloud.api.key.secret=dGq2cGN1LhLybhLy0EK0FpX-BQ0

# Configuración api Stripe
stripe.secret-key=sk_test_51T57Y9FTrFhsWQDFOczOevKugbeTVBrjpmFc9XqvDHk7x5lnRIxu8O6aI46aBXkjlEAwgoq3kQyJ5wUc7sxuuxh500bQgEu28O
stripe.webhook-secret=whsec_c821ca568d57827fac182d40c92e7686040f127ead5931b4b0a51720e5c64b46
stripe.currency=cop