### Login
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "david.posso@example.com",
  "contrasena": "Passw0rd1"
}

> {% client.global.set("auth_token", response.body.token) %}

### Crear usuario (201 Created)
POST http://localhost:8080/api/auth/registro
Content-Type: application/json

{
  "nombre": "David Pedraza",
  "email": "david.pedraza@example.com",
  "contrasena": "Passw0rd1",
  "telefono": "3001234567",
  "foto": null,
  "fechaNacimiento": "1994-03-10",
  "rol": "Huesped"
}

### Cambiar contraseña (PATCH) (200) — usa CambioContrasenaDTO
PATCH http://localhost:8080/api/usuarios/1ccd6ad2-6ab3-4987-996c-99bdffd2905d/contrasena
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImRhdmlkLnBvc3NvQGV4YW1wbGUuY29tIiwibmFtZSI6IkRhdmlkIFBvc3NvIiwicm9sZSI6IlJPTF9IdWVzcGVkIiwic3ViIjoiMWNjZDZhZDItNmFiMy00OTg3LTk5NmMtOTliZGZmZDI5MDVkIiwiaWF0IjoxNzU5NDQ3NzIwLCJleHAiOjE3NTk0NTEzMjB9.4Zg-_Ujg6vl6nKR_gHjBMlYjG9wG26pTbnDuSVRpRZs

{
  "contrasenaActual": "Passw0rd1",
  "contrasenaNueva": "Pass0123"
}

### Editar usuario (PUT) (200)
PUT http://localhost:8080/api/usuarios/1ccd6ad2-6ab3-4987-996c-99bdffd2905d
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImRhdmlkLnBvc3NvQGV4YW1wbGUuY29tIiwibmFtZSI6IkRhdmlkIFBvc3NvIiwicm9sZSI6IlJPTF9IdWVzcGVkIiwic3ViIjoiMWNjZDZhZDItNmFiMy00OTg3LTk5NmMtOTliZGZmZDI5MDVkIiwiaWF0IjoxNzU5NDQ3NzIwLCJleHAiOjE3NTk0NTEzMjB9.4Zg-_Ujg6vl6nKR_gHjBMlYjG9wG26pTbnDuSVRpRZs

{
  "nombre": "David Posso",
  "telefono": "3001234567",
  "foto": null,
  "fechaNacimiento": "1994-03-10",
  "rol": "Huesped"
}
